---
name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # echo "$DOCKER_TOKEN" | docker login registry.gitlab.com --username "$DOCKER_USER" --password-stdin
      # - name: Login to GitLab
      #   uses: docker/login-action@v1
      #   with:
      #     registry: registry.gitlab.com
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup for Testing
        run: |
          cp .env.example .env
          cp .env.example .env.test
          npm install --include=dev

      - name: Test
        run: |
          npm run unit-test
          npm run react-test
